server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
    url: jdbc:postgresql://10.140.0.2:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
#    host: localhost
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672
